### ISSUE TITLE
script/run-docker: Handle bind-mounting extra files

### ISSUE THREAD

**Issue by rye** [StoDevX/cs251-toolkit#37]
For specs like `hw3`, students are required to use something that is local to the link computers.

We can `scp` this over fairly easily, but we need a mechanism to bind-mount so that builds don't error.  Alternatively, we could just copy the entire `cs251` directory and bind-mount it properly.

**Comment by hawkrives** [comment]
I might just stick it into the supporting/hw3 folder in the specs repo

Uh

Because I definitely did something about this last time I graded

I will see if I can remember what I did.

**Comment by rye** [comment]
The solution that could work with this script is to just bind-mount needed files to needed locations to grade homework.  I'd venture that it might make sense to include some kind of requirement of files being where they're needed as a precondition to abort grading if the environment is wrong.

**Comment by hawkrives** [comment]
I'm pretty sure that my workaround for hw3 was to just run the toolkit on the lab machines.

Sure, we could add a thing to the specs for "required extra-submission files" or something.

**Comment by rye** [comment]
Yeah. It's always a possibility to just `scp` the file over and then bind-mount the file (e.g. `/home/users/cs251/binary.h`, which is included from the hw submissions) into the appropriate location on the container.

Mostly, I just need to add an option to do this to the script, since it's a Docker-related thing.

**Comment by hawkrives** [comment]
```yaml
---
assignment: hw3

compilers:
  - &cpp 'g++ --std=c++11 $@ -o $@.exec'

dependencies:
  - /home/users/cs251/binary.h

files:
  - [ arithmetic.cpp, *cpp ]
  - [ guard.cpp, *cpp ]
  - [ miscOperators.cpp, *cpp ]
  - [ precedence.cpp, *cpp ]

tests:
  - [ arithmetic.cpp, $@.exec ]
  - [ guard.cpp, $@.exec ]
  - [ miscOperators.cpp, $@.exec ]
  - [ precedence.cpp, $@.exec ]
```
